//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sept2023WebAppMVC.Enitites
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Firstname { get; set; }
        public string Username { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<long> MobileNumber { get; set; }
    }
}
